// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@1.0.0";

// src/lib/mcp/tools/search-listings.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.49.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-listings.ts
var COLUMNS = "id, brand, model, year, price, mileage, fuel_type, transmission, body_type, power, co2, euro_norm, location, seller_type, car_pass_status, photos, created_at";
var search_listings_default = defineTool({
  name: "search_listings",
  title: "Rechercher des annonces",
  description: "Recherche des annonces de voitures d'occasion publi\xE9es sur AutoRA.be (march\xE9 belge). Filtres optionnels : marque, mod\xE8le, carburant, prix max, ann\xE9e min, kilom\xE9trage max, localisation.",
  inputSchema: {
    brand: z.string().optional().describe("Marque, ex. BMW"),
    model: z.string().optional().describe("Mod\xE8le, ex. Serie 3"),
    fuel_type: z.string().optional().describe("Carburant, ex. essence, diesel, electrique, hybride"),
    max_price: z.number().optional().describe("Prix maximum en euros"),
    min_year: z.number().optional().describe("Ann\xE9e de mise en circulation minimum"),
    max_mileage: z.number().optional().describe("Kilom\xE9trage maximum"),
    location: z.string().optional().describe("Ville ou r\xE9gion en Belgique"),
    limit: z.number().optional().describe("Nombre de r\xE9sultats (d\xE9faut 20, max 50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const limit = Math.min(Math.max(Math.trunc(input.limit ?? 20), 1), 50);
    let query = supabase.from("car_listings_public").select(COLUMNS).order("boost_rank", { ascending: false, nullsFirst: false }).order("created_at", { ascending: false }).limit(limit);
    if (input.brand) query = query.ilike("brand", `%${input.brand}%`);
    if (input.model) query = query.ilike("model", `%${input.model}%`);
    if (input.fuel_type) query = query.ilike("fuel_type", `%${input.fuel_type}%`);
    if (input.location) query = query.ilike("location", `%${input.location}%`);
    if (typeof input.max_price === "number") query = query.lte("price", input.max_price);
    if (typeof input.min_year === "number") query = query.gte("year", input.min_year);
    if (typeof input.max_mileage === "number") query = query.lte("mileage", input.max_mileage);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const results = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify({ count: results.length, results }, null, 2) }],
      structuredContent: { count: results.length, results }
    };
  }
});

// src/lib/mcp/tools/get-listing.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_listing_default = defineTool2({
  name: "get_listing",
  title: "D\xE9tail d'une annonce",
  description: "R\xE9cup\xE8re la fiche compl\xE8te d'une annonce AutoRA.be \xE0 partir de son identifiant (specs, prix, Car-Pass, localisation, photos).",
  inputSchema: { id: z2.string().describe("Identifiant UUID de l'annonce") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("car_listings_public").select(
      "id, brand, model, year, price, mileage, fuel_type, transmission, body_type, doors, color, power, puissance_cv, co2, co2_cycle, fuel_consumption, euro_norm, mma, features, description, location, seller_type, car_pass_status, car_pass_date, ct_valid, maintenance_book_complete, photos, created_at"
    ).eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Annonce introuvable." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { listing: data }
    };
  }
});

// src/lib/mcp/tools/my-listings.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z3 } from "npm:zod@^3.25.76";
var my_listings_default = defineTool3({
  name: "my_listings",
  title: "Mes annonces",
  description: "Liste les annonces publi\xE9es par l'utilisateur connect\xE9 sur AutoRA.be, avec leur statut de mod\xE9ration (approved, pending, rejected, sold).",
  inputSchema: {
    status: z3.string().optional().describe("Filtre de statut : approved, pending, rejected ou sold")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("car_listings").select("id, brand, model, year, price, mileage, status, car_pass_status, location, created_at, updated_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(50);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const results = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify({ count: results.length, results }, null, 2) }],
      structuredContent: { count: results.length, results }
    };
  }
});

// src/lib/mcp/tools/my-favorites.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z4 } from "npm:zod@^3.25.76";
var my_favorites_default = defineTool4({
  name: "my_favorites",
  title: "Mes favoris",
  description: "Liste les v\xE9hicules enregistr\xE9s dans le garage (favoris) de l'utilisateur connect\xE9 sur AutoRA.be.",
  inputSchema: {
    limit: z4.number().optional().describe("Nombre de r\xE9sultats (d\xE9faut 20, max 50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(Math.trunc(limit ?? 20), 1), 50);
    const { data: favorites, error } = await supabase.from("favorites").select("listing_id, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(max);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const ids = (favorites ?? []).map((f) => f.listing_id).filter(Boolean);
    let listings = [];
    if (ids.length > 0) {
      const { data, error: listErr } = await supabase.from("car_listings_public").select("id, brand, model, year, price, mileage, fuel_type, location, photos").in("id", ids);
      if (listErr) return { content: [{ type: "text", text: listErr.message }], isError: true };
      listings = data ?? [];
    }
    return {
      content: [{ type: "text", text: JSON.stringify({ count: listings.length, favorites: listings }, null, 2) }],
      structuredContent: { count: listings.length, favorites: listings }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jbdsjqoonpieusfvkhyo";
var mcp_default = defineMcp({
  name: "autora",
  title: "AutoRA",
  version: "0.1.0",
  instructions: "Outils AutoRA.be, la marketplace automobile belge. `search_listings` recherche des voitures d'occasion publi\xE9es, `get_listing` renvoie la fiche compl\xE8te d'une annonce, `my_listings` liste les annonces de l'utilisateur connect\xE9 et `my_favorites` son garage. Toutes les donn\xE9es sont belges (Car-Pass, normes Euro, LEZ).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_listings_default, get_listing_default, my_listings_default, my_favorites_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@1.0.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
